services:
  - type: web
    name: mailboxes-relacionador
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app_web.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: RENDER
        value: true
